# Start from the official MySQL 8 image
FROM mysql:8

# Set environment variables for root password and MySQL database
# ENV MYSQL_ROOT_PASSWORD=root_password
# ENV MYSQL_DATABASE=mydatabase
# ENV MYSQL_USER=username
# ENV MYSQL_PASSWORD=password

# Copy any initialization SQL files to Docker's entrypoint location
# COPY init.sql /docker-entrypoint-initdb.d/

# Expose MySQL port (optional, MySQL defaults to 3306)
EXPOSE 3306